name: Greeting on variable day

on:
  [push]
env:
  DAY_OF_WEEK: Today

jobs:
  testing_runner:
    runs-on: linux-runner
    env:
      Greeting: Hello
    steps:
      - name: "Say Hello New Job it's Today"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        env:
          First_Name: New Job
