name: List Files

on:
  [push]

jobs:
  testing_runner:
    runs-on: linux-runner
    env:
      command: ls
    steps:
      - name: "run commands with variables"
        run: $command $path
        env:
          path: /home/ubuntu/
